### ISSUE TITLE
Home Assistant mqtt changes

### ISSUE THREAD

**Issue by darkxst** [roleoroleo/sonoff-hack#102]
There were some breaking changes that alter mqtt configurations in Home Assistant 2022.06. Support for old format will be completely removed soon. Examples on the wiki can be updated to the following for new format (and a minor fix for payload values).

```
mqtt:
  binary_sensor:
    - state_topic: "home-assistant/kitchen/motion_detection"
      name: "Motion detection - kitchen"
      payload_on: "motion_start"
      payload_off: "motion_stop"
      qos: 1
```

```
mqtt:
  camera:
    - topic: "home-assistant/kitchen/motion_detection_image"
      name: "Motion detection image - kitchen"
```
